### PR TITLE
Add MonetaryUnit Support

### PR DESCRIPTION
**Pull request by upgradeadvice**
Adds MonetaryUnit support.

### CODE REVIEW

**Comment by erasmospunk** [comment]
Looks good.

Could you make a pull request with the vector version of the icon to https://github.com/erasmospunk/crypto-icons?

Also can you make your electrum servers run on port 5033? We will CNAME `electrum1.monetaryunit.org` and `electrum2.monetaryunit.org` to `mue-cce-1.coinomi.net` and `mue-cce-2.coinomi.net` (currently we leave 2 seed nodes, in a later release the number of nodes will be dynamic). So the CoinAddress initialization should be like the following:

```
new CoinAddress(MonetaryUnitMain.get(), new ServerAddress("mue-cce-1.coinomi.net", 5033),
                                        new ServerAddress("mue-cce-2.coinomi.net", 5033))
```

**Comment by upgradeadvice** [comment]
Servers updated
Use new icons https://github.com/erasmospunk/crypto-icons/pull/4

**Comment by upgradeadvice** [comment]
Merged upstream

**Comment by bbizzy** [comment]
Would be VERY cool to get MonetaryUnit included into the Coinomi wallet.
Please let us know if we can do anything else to help?
Thanks :)

**Comment by erasmospunk** [comment]
Sorry for the late reply. Everything looks good except the icon, the previous is much better, you can use that for the icon set https://github.com/erasmospunk/crypto-icons

One last thing. We are moving the electrum server codebase to a unified version called [Mercury](https://github.com/Kefkius/encompass-mercury) could you please make a pull request there? Read the [info](https://github.com/Kefkius/encompass-mercury/blob/master/src/chains/README.md) to add a new chain support.

**Pull request closed without merging**
