### PR TITLE
Auroracoin support

### PR DESCRIPTION
**Pull request by BioMike**
Hello,

I'm a member of the Auroracoin dev team and would like to have this coin included in coinomi-android.
I've already send a PR to Satoshilabs for inclusion in slip-0044: https://github.com/satoshilabs/slips/pull/6

How quick can we get Auroracoin included in a downloadable wallet (in the app store)?

Thank you in advance.

### CODE REVIEW

**Comment by BioMike** [comment]
The PR for BIP44 inclusion has been merged.

**Comment by auroracoin-tools** [comment]
Hello, any news? looking forward to use my favorite wallet with my favorite coin :+1:

**Comment by auroracoin-tools** [comment]
+1 for this merge.

**Comment by Skarfurinn** [comment]
+1

**Comment by erasmospunk** [comment]
Sorry for the delay.

I am testing this but the electrum server seems to be down?

**Comment by BioMike** [comment]
Server crashed last week (and the secondary server was temporarily shut down by its admin) and electrum wasn't automatically restarted. I fired it up now, so you should be ok. Backup should soon come online again as well.

**Comment by erasmospunk** [comment]
@BioMike I sent yesterday a test transaction and it worked. An hour later [another one](http://insight.auroracoin.io/tx/196d7927aedf28cdb76cdd16d5fcccca4a993afc5eb5e7803bfa193367e33e44) but it doesn't appear in the electrum server. When the server crashes, what kind of error do you get?

**Comment by ny2cafuse** [comment]
Electrum2.auroracoin.is is back up and running.  Sorry for the downtime.

**Comment by erasmospunk** [comment]
@ny2cafuse is it on port 50001? Still cannot connect.

**Comment by ny2cafuse** [comment]
Should be up.  When I spun up the snapshot of the server, I had the port closed.  I'm seeing a session coming through now.

**Comment by BioMike** [comment]
The server crash was the whole (VPS) system, not electrum specific. It is still running fine, although I get the following errors:

ERROR:electrum:recv error: error(9, 'Bad file descriptor')

Is this something to worry about?

**Comment by BioMike** [comment]
I got the latest electrum server checkout from your repo, it's syncing now. Takes about 40 minutes to get fully synced.

**Comment by BioMike** [comment]
Here some more info. The electrum server I was running was from the @erasmospunk repo from halfway December last year. I just noticed that you had a new version in repo (last update from Feb this year), which I'm now syncing. The 40 minutes for syncing were a bit optimistic, the eta is now suggesting about 210 minutes.

**Comment by erasmospunk** [comment]
@ny2cafuse electrum2.auroracoin.is is working
@BioMike what branch are you using?

**Comment by BioMike** [comment]
@erasmospunk 'master' branch, and still syncing.

**Comment by erasmospunk** [comment]
@ny2cafuse @BioMike the electrum servers are down again, probably need some debugging. If you need help, send me to john at coinomi.com

**Comment by ny2cafuse** [comment]
@erasmospunk, emailed you with additional info.

**Comment by BioMike** [comment]
@erasmospunk I'm having problems syncing on my VPS due to memory constrains. I've reduced the pruning limit, hoping that will help. I've got a few more tricks up my sleeve, but if those don't work I'll let you know.

**Comment by BioMike** [comment]
@erasmospunk electrum server seems to be running fine now for the last day. Could you have another check on it?

**Comment by erasmospunk** [comment]
Manually merged https://github.com/Coinomi/coinomi-android/commit/1420e39a39e7640309b8bc2aea29d3bc80691e2e

**Pull request closed without merging**
