### PR TITLE
Commit Richcoin Changes

### PR DESCRIPTION
**Pull request by ahmedbodi**
Add Richcoin

### CODE REVIEW

**Comment by Comodore125** [comment]
Dont add, this is totely unnecesary coin

**Comment by GeorgeKimionis** [comment]
@Comodore125 care to elaborate?

**Comment by ahmedbodi** [comment]
Weather you find it unnecessary or not is besides the point. Users of the coin will and I've spoken to john / eramospunk about adding the coin and he was happy for it to be added

**Comment by GeorgeKimionis** [comment]
@ahmedbodi I second that.

**Comment by ahmedbodi** [comment]
any news on this being merged?

**Comment by erasmospunk** [comment]
Was going to merge this but noticed that the token symbol is "USD". Is this correct?

If that is the case, it will confuse a lot of people. I suggest switching to RCH or RICH symbols.

**Comment by ahmedbodi** [comment]
Correct, that was what it was. But yobit has listed it as RICHX so i will change it to that

**Comment by ahmedbodi** [comment]
This ready to be merged @erasmospunk

**Comment by erasmospunk** [comment]
manually merged https://github.com/Coinomi/coinomi-android/commit/87da17de4ecc496d5f3d53f65daf5b2dd14dd2b5

**Pull request closed without merging**
