### PR TITLE
Asiacoin

### PR DESCRIPTION
**Pull request by fsb4000**
https://github.com/satoshilabs/docs/pull/56
Thank you!

### CODE REVIEW

**Comment by erasmospunk** [comment]
Looks good. The only thing that is missing is to add a vector icon to https://github.com/erasmospunk/crypto-icons

**Comment by fsb4000** [comment]
Done, https://github.com/erasmospunk/crypto-icons/pull/10

**Comment by erasmospunk** [comment]
Looks good. Could you send us some AC to make some tests? AH8sfKqcJir4VQzzStmZKLCzp2twPEQSzJ

**Comment by erasmospunk** [comment]
@fsb4000 also to you have domain names for the 185.81.167.185 and 185.81.165.138 addresses?

**Comment by fsb4000** [comment]
@erasmospunk Sure, sent https://chainz.cryptoid.info/ac/tx.dws?2579368.htm
I don't have domain names for the 185.81.167.185 and 185.81.165.138.

**Comment by fsb4000** [comment]
Oh, today I saw that you already added Asiacoin: https://github.com/Coinomi/coinomi-android/commit/6ebe39c622f457547ac033bcdf87a2e8cfc42918
Thank you!

**Pull request closed without merging**
