### PR TITLE
Added support for neoscoin

### PR DESCRIPTION
**Pull request by Extrememist**
I added neoscoin. i used a vector for the logos, to correct what you told me to, and the electrum-server i used is right here https://github.com/neoscoin/neos-electrum-server for the testnet i modified. the config that it generates and added the neoscoin testnet details. and it worked. Hopefully this is all that was required if not let me know

### CODE REVIEW

**Comment by Extrememist** [comment]
I only just noticed that you edited version src. but will mine still pass i have fixed the logos :)

**Comment by erasmospunk** [comment]
I added the modified icons, can you create a single commit on top of that? For the time being we will not add the testnet version in the android wallet but you can leave the NeoscoinTest coin type in the core module for the future.

Also the bip44Index is incorrect, it must be registered [here](https://github.com/satoshilabs/docs/blob/master/slips/slip-0044.rst) (notice [this](https://github.com/satoshilabs/docs/pull/25) pending a pull request) but we can register it after we test it. The BIP44 testnet coins are always on index 1, notice the Bitcoin testnet CoinType.

Have you used a vanilla Electrum server without any modifications?

**Comment by Extrememist** [comment]
Since im new to using github, i hope i did what you asked correctly. and i did use vanilla electrum but we modified our own version so we. could have it straight for neos so. the one i linked when i started this pull request

**Comment by erasmospunk** [comment]
The `bip44Index` 22 is used by Monacoin.

Also you still need to do a git rebase to create a single commit and then override this pull request. Remember to pull the latest changes.

Other than that it looks good.

**Comment by Extrememist** [comment]
Infernoman is closing this pull request. Everything should be fixed with pull request #30

**Pull request closed without merging**
