### PR TITLE
added DOGED

### PR DESCRIPTION
**Pull request by doged**
added support for DogecoinDark, sorry for the delay, today is our 1 year birthday, and i've been really busy working on the new upcoming core wallet =]

### CODE REVIEW

**Comment by doged** [comment]
ok didnt realize the first time that other coins were added, so i did a fresh update. thanks for your consideration @erasmospunk

**Comment by erasmospunk** [comment]
Could you move the electrum-doged.space port from 50001 to 5036? Also for redundancy a second server is needed.

**Comment by doged** [comment]
ok i will post those monday afternoon

**Comment by doged** [comment]
@erasmospunk i have another electrum server up and running, but i also have other services that are connecting to 50001. is there any reason its necessary to change the port? i can add another for redundancy, that is no problem, but changing the port would require changing a few other services as well..

**Comment by erasmospunk** [comment]
@doged ok, you can leave the port as is. Regarding the second electrum server, what is the hostname?

**Comment by doged** [comment]
@erasmospunk 104.131.79.255:50001   havent bothered getting a domain name for it.. heh.. been really busy working on our wallet upgrade. thanks for adding us!

**Comment by erasmospunk** [comment]
@doged when you have a hostname for the second server write it here. Btw the code of this pull request is already merged and the coin available in Coinomi.

**Comment by erasmospunk** [comment]
@doged the electrum server is down. Could you please send us a message to support at coinomi.com to have your contact email.

**Comment by doged** [comment]
yes, doged is in the process of rebranding to VERGE, and the new server will be up tomorrow. sorry I can't restart it right now, I'm actually at the hospital, my daughter is being born any moment now :) I'll make a pull request with the changes tomorrow or Friday the latest!

**Comment by erasmospunk** [comment]
@doged Verge sounds like a nice name. Can you still send us a message so we can have a direct contact with the developer team.

Congrats for your daughter!

**Comment by erasmospunk** [comment]
manually merged https://github.com/Coinomi/coinomi-android/commit/ecbee191010f1c34191c46b643ca2f60eee2974b

**Pull request closed without merging**
