### PR TITLE
Support for ParkByte

### PR DESCRIPTION
**Pull request by parkbyte**
ParkByte Support added

### CODE REVIEW

**Comment by erasmospunk** [comment]
Could you submit the vector icon to the [icon set](https://github.com/erasmospunk/crypto-icons)?

We are moving the electrum server codebase to a unified version called [Mercury](https://github.com/Kefkius/encompass-mercury) could you please make a pull request there? Read the [info](https://github.com/Kefkius/encompass-mercury/blob/master/src/chains/README.md) to add a new chain support.

**Comment by erasmospunk** [comment]
It is possible to include ParkByte in the next release. There are a couple of things that need to be done before that:

- Submit the vector icon to the [icon set](https://github.com/erasmospunk/crypto-icons).
- Change the electrum server port to `5035`

**Comment by parkbyte** [comment]
Maybe abit late for your next release but Electrum server ports have now been changed to 5035 & Icon set has been submitted

I will look to move the electrum server codebase to Mercury in the coming weeks, Thanks

**Comment by erasmospunk** [comment]
Just noticed that you forgot to register your coin for the BIP44 standard: https://github.com/satoshilabs/docs/blob/master/slips/slip-0044.rst

Please make a pull request there and then update this pull request with the correct index.

**Comment by parkbyte** [comment]
Registered and updated

**Comment by erasmospunk** [comment]
Thanks!

**Pull request merged**
