### PR TITLE
adding Bata (BTA) to Coinomi

### PR DESCRIPTION
**Pull request by BTA-BATA**

### CODE REVIEW

**Comment by vbecas** [comment]
Could you please fix the imports at BatacoinMain.java and also remove the unneeded (); at line 19

**Comment by BTA-BATA** [comment]
fixed as per vbecas request.

**Comment by BTA-BATA** [comment]
Thank you - this has been done.

**Comment by erasmospunk** [comment]
I am merging now but I noticed that you didn't register a BIP44 index. Can you make a pull request here:

https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by BTA-BATA** [comment]
Sorry about the delay in responding
https://github.com/satoshilabs/slips/pull/12

On Thu, Apr 14, 2016 at 4:18 AM, John L. Jegutanis <notifications@github.com

**Comment by BTA-BATA** [comment]
lol I am useless :'(

**Comment by erasmospunk** [comment]
@BTA-BATA I noticed that you register the BIP44 index 89 so I am going to change it also here.

**Comment by erasmospunk** [comment]
@BTA-BATA also can you check the electrum server, why is it down?

**Comment by erasmospunk** [comment]
@BTA-BATA seems good now

**Comment by BTA-BATA** [comment]
thanks

On Sat, Apr 16, 2016 at 1:03 AM, John L. Jegutanis <notifications@github.com

**Comment by erasmospunk** [comment]
manually merged https://github.com/Coinomi/coinomi-android/commit/002d36b84bf0307e700a5da1cff57ec7a1640605

**Pull request closed without merging**
