### PR TITLE
Feature/efl support

### PR DESCRIPTION
**Pull request by AmazingDreams**
I added support for the e-Gulden to Coinomi.

Some notes:
- Currently the Electrum server is only running on one instance.
- Waiting on ShapeShift.io to add us

Please let me know if there is anything more I should include.

### CODE REVIEW

**Comment by erasmospunk** [comment]
Thanks for the pull request and sorry for the delay.

The servers seem to be down or there some kind of connectivity error (maybe firewall?). Could you move the port from 50001 to 5037?

**Comment by AmazingDreams** [comment]
I temporarily shut down the servers and deregistered the IP addresses. Servers are currently running on 52.31.4.31 and 52.19.135.107. Should I still change the ports?

**Comment by galimi** [comment]
I'm unable to send or show updated balances for Dash (all other coins seem fine).
Is it related to this?

**Comment by AmazingDreams** [comment]
@galimi not directly as this is about a different coin, but perhaps the Dash servers are offline.

**Comment by galimi** [comment]
@AmazingDreams OK, thanks.  Any idea on who I could reach out to for this?

**Comment by AmazingDreams** [comment]
No sorry, I think your best bet would be @erasmospunk. He'll probably read these messages shortly.

**Comment by erasmospunk** [comment]
@AmazingDreams it looks mostly good. The last thing that need to be fixed is the bip44 index, you should register here https://github.com/satoshilabs/docs/blob/master/slips/slip-0044.rst

**Comment by AmazingDreams** [comment]
See https://github.com/satoshilabs/docs/pull/58

**Comment by AmazingDreams** [comment]
@erasmospunk the pull request got merged ;)

**Comment by erasmospunk** [comment]
@AmazingDreams sorry for the delay. I am merging now but the electrum servers are down, can you check?

**Comment by erasmospunk** [comment]
manually merged https://github.com/Coinomi/coinomi-android/commit/f75e71aa6da1820ca3e39ee3946d1fa2ab032e25

**Pull request closed without merging**
