### PR TITLE
added the Canada eCoin

### PR DESCRIPTION
**Pull request by koad**
Awesome, will do! Thanks!

### CODE REVIEW

**Comment by erasmospunk** [comment]
Thanks for the pull request.

**Comment by erasmospunk** [comment]
Everything looks good.

We are moving the electrum server codebase to a unified version called [Mercury](https://github.com/Kefkius/encompass-mercury) could you please make a pull request there? Read the [info](https://github.com/Kefkius/encompass-mercury/blob/master/src/chains/README.md) to add a new chain support.

**Comment by erasmospunk** [comment]
@koad we cannot connect to your electrum servers:

```
nc: connectx to alberta.canadaecoin.net port 5033 (tcp) failed: Connection refused
nc: connectx to ontario.canadaecoin.net port 5033 (tcp) failed: Connection refused
```

**Comment by koad** [comment]
Give me an hour as I am on my way back from work.

I think the port is different, its possible that the servers are on a port
that was available when we put them up but then was used for another coin
within Coinomi so we went up by one.

I wasn't actually expecting a merge so soon, we figured we wouldn't see a
merge until the mercury servers went live which are on those ports on a
pair of different servers.

I will make sure the current electrum servers listen to those ports when I
get home.

Also, with the mercury servers,shall I just replace the electrum servers
when they are alive and proven well?

Jason.

**Comment by erasmospunk** [comment]
Sounds like a good plan. The port should be 5033.

About Mercury, that is the idea. For now the wallet can use the existing servers and when you have your Mercury ready just switch them, one after the other. The only requirement is to keep the domain and the ports the same.

**Comment by koad** [comment]
Thanks John,

I took a look at those ports and they seem to be fine and when I do a test
similar to yours I get the same results even though my dev Coinomi connects
no problem.

Can you show me an example of the desired output of netcat so I can try to
replicate?

Thanks in advance John, sorry for eating up your time here.

Jason

**Comment by erasmospunk** [comment]
Maybe a firewall issue?

I try with:
```
➜  nc -v alberta.canadaecoin.net 5033
nc: connectx to alberta.canadaecoin.net port 5033 (tcp) failed: Connection refused
```

**Comment by koad** [comment]
OK, I'm gonna scarf some lasagne, put the kids to bed, then I will sort
this out.

Thanks John,  I'll send word when I have a resolution.

Jason

**Comment by koad** [comment]
You were absolutely right. It was the firewall.

It seems I needed some cheesy pasta to kick start my brain again after the
long day to see the error. :)

They are working now, on port 5033.


Thanks for the assistance here John,  much appreciation.


Jason.

On Thu, Aug 27, 2015 at 9:50 PM, John L. Jegutanis <notifications@github.com

**Comment by erasmospunk** [comment]
Glad to hear that and can confirm that it works.

Could you send me a couple of cents to try it out? CWG8BMr39sFnJbqNqqAp6HHXtz86qg8dRR
And give me your address so I send you back some.

I am releasing the beta now so expect the normal release in a couple of days.

**Comment by koad** [comment]
Done and done,

I sent you 10 Canadian Dollars worth using my Coinomi Wallet :)

I love it,

Keep the coins, use them for testing or whatever, :)


Jason.

**Comment by erasmospunk** [comment]
Thanks! Glad you like it.

If you want to grab the v1.5.20 beta, follow the instructions [here](https://play.google.com/apps/testing/com.coinomi.wallet). It could take some hours for the new version to appear so maybe it is better if you do it tomorrow. [Here](https://github.com/Coinomi/coinomi-android/releases/tag/v1.5.20) is the same APK that we are testing to release in a few days.

**Comment by koad** [comment]
:)  Thank you John.

The team and I are very grateful.  Please feel free to reach out if you
need anything at all.

Jason Zvaniga

**Pull request merged**
