### PR TITLE
rebranded, $DOGED -> $XVG

### PR DESCRIPTION
**Pull request by vergecurrency**
rebranded dogecoindark/doged to verge/xvg, added new icons.

will have another 1 or 2 electrum servers up shortly for redundancy.

cheers @erasmospunk

### CODE REVIEW

**Comment by erasmospunk** [comment]
@BTA-BATA @justinvforvendetta @vergecurrency 

We are doing some tests and there seems to be a problem with your electrum server. [This transaction](https://www.blockexperts.com/xvg/tx/60cea8c9c38de5ecb6d0cebc3d3039b73346b8b3e7851143547b2087c60d5449) seems to be confirmed but when querying the electrum server:

`{"params": ["DTV8Q59BbD3NeSnfLAUynQumCHDyPGJpYw"], "id": 0, "method": "blockchain.address.get_history"}`

we get:

`{"id": 0, "result": [{"tx_hash": "60cea8c9c38de5ecb6d0cebc3d3039b73346b8b3e7851143547b2087c60d5449", "height": 0}]}`

The height 0 means that the transaction was not confirmed according to that server.

Also, there appears to be a fork on block height 276928. The electrum server reports `0000000000012e08fa935f9d41f354744f2347843266b0286f376ecc42507069` while the block explorer reports `00000000000264ddc0f36c2e068ed42150505d6f3e71982bb0968b8713890afb`.

**Comment by vergecurrency** [comment]
are you sure its not just about to do a reorg?

https://www.blockexperts.com/xvg/tx/60cea8c9c38de5ecb6d0cebc3d3039b73346b8b3e7851143547b2087c60d5449

i see 0 confirms so far, but i have a feeling itll be fine. we have been getting hit with massive hashpower from china, who is forking, then reorganizing with new blocks..

**Comment by vergecurrency** [comment]
"difficulty" : 10028.25665453,
 "networkhashps" : 208711198677, (about 208gh/s right now)

**Comment by vergecurrency** [comment]
i think we're going to switch algo soon, since this is happening to all scrypt coins. those dang farms, man.

**Comment by vergecurrency** [comment]
the rest of the network still thinks the next block is 276930 as well. a reorg will happen soon.

**Comment by vergecurrency** [comment]
re-organization happened.

**Comment by erasmospunk** [comment]
I am merging this but I noticed that the electrum server is down

**Comment by vergecurrency** [comment]
we just went multi algo, so im literally working on our electrum server right now. it will be the same address

**Comment by erasmospunk** [comment]
manually merged https://github.com/Coinomi/coinomi-android/commit/ecbee191010f1c34191c46b643ca2f60eee2974b

**Comment by erasmospunk** [comment]
@vergecurrency any update for the electrum servers?

**Comment by vergecurrency** [comment]
yeah finishing up porting it for multi algo. wasnt easy. i assure you it will be up permanently soon. and ill add a second for redundancy.

**Comment by erasmospunk** [comment]
Sounds good. If you've made modifications to the Electrum server, post the source code somewhere please.

**Comment by vergecurrency** [comment]
@erasmospunk we're back up and running. i need to make an update to my coin daemon on that box, but itll be up permanently within an hour or two. thanks for your patience =]

**Comment by erasmospunk** [comment]
@vergecurrency the electrum server seems to be stuck at block 384746. Furthermore the Electrum server that you are using does not have the `block_height` property when calling the `blockchain.headers.subscribe` method.

If you would like us to host and monitor the servers, send an email to george at coinomi.com.

**Comment by vergecurrency** [comment]
@erasmospunk think i got that fixed now, sorry about that.

**Pull request closed without merging**
