### PR TITLE
Add Zoom Support

### PR DESCRIPTION
**Pull request by upgradeadvice**
PR for SLIP-0044 (32) https://github.com/satoshilabs/docs/pull/38
Relevant electrum-server config network section:
```
[network]
pubkey_address = 103
script_address = 231
genesis_hash = 5572f72208ed0a9682a3d54e59b98c65e9367d64591d5828b7521fde8bfd195b
```

### CODE REVIEW

**Comment by bitcoindogg** [comment]
Be really nice to have Zoom part of the project.

**Comment by bitcoindogg** [comment]
Be really nice to have Zoom part of the project

**Comment by bitcoindogg** [comment]
Add Zoom Support by upgradeadvice · Pull Request #38 · Coinomi/coinomi-android · GitHub

**Comment by erasmospunk** [comment]
The coin icon does not match the style of the application, it should be flat, simple without many details, similar to how other coin icons look. Could you make a pull request with the vector version of the icon to https://github.com/erasmospunk/crypto-icons?

Can you make your electrum servers run on port 5034? Also 2 electrum servers are needed and they must have a domain names so that we can create CNAMEs for `zoom-cce-1.coinomi.net` and `zoom-cce-2.coinomi.net`.  The CoinAddress initialization would look similar to the following:

```
new CoinAddress(ZoomMain.get(), new ServerAddress("zoom-cce-1.coinomi.net", 5034),
                                new ServerAddress("zoom-cce-2.coinomi.net", 5034))
```

**Comment by upgradeadvice** [comment]
Added flat zoom icons https://github.com/erasmospunk/crypto-icons/pull/4
New electrum servers are:
```
electrum1.zoomcoin.co 5034
electrum2.zoomcoin.co 5034
```

**Comment by upgradeadvice** [comment]
Merged upstream

**Comment by erasmospunk** [comment]
Also here a pull request to [Mercury](https://github.com/Kefkius/encompass-mercury) is needed.

**Pull request closed without merging**
